steps:  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_MODEL_NAME}:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_MODEL_NAME}:${SHORT_SHA}']
  - name: google/cloud-sdk
    args: ['gcloud', 'beta', 'run', 'jobs', 'create', '${_MODEL_NAME}-${SHORT_SHA}', '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_MODEL_NAME}:${SHORT_SHA}', '--region', 'us-central1', '--memory', '2G']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/flight-predict:${SHORT_SHA}
timeout: 3600s

